"""snapshot.refresh(): one file per enabled source, stale on failure, removed sources deleted;
`snapshot --source NAME` refreshes one and leaves the rest alone."""
import json
import os
import shutil
import tempfile
import unittest
from pathlib import Path
from unittest import mock

from remainderbot import __main__ as cli
from remainderbot import snapshot, sources
from remainderbot.adapters import ADAPTERS, SourceError, adapter
from remainderbot.config import Config


def table(**fields) -> str:
    """One [[sources]] table; JSON strings, ints, and booleans are valid TOML values."""
    return "[[sources]]\n" + "".join(f"{k} = {json.dumps(v)}\n" for k, v in fields.items())


def fake(src, ctx):
    if src.get("fail"):
        raise SourceError("fake: exit 1: down")
    if src.get("crash"):
        raise KeyError("oops")
    return src["text"]


class Refresh(unittest.TestCase):
    def setUp(self):
        self.td = Path(tempfile.mkdtemp())
        self.addCleanup(shutil.rmtree, self.td, True)
        registry = mock.patch.dict(ADAPTERS)
        registry.start()
        self.addCleanup(registry.stop)
        adapter("fake", required={"text": str}, optional={"fail": bool, "crash": bool})(fake)
        self.config = Config(repo_dir=self.td)
        self.snap = self.config.snapshot_dir
        self.logs = []

    def configure(self, *tables: str):
        (self.td / "sources.toml").write_text("version = 1\n" + "".join(tables))

    def refresh(self):
        return snapshot.refresh(self.config, self.logs.append)

    def body(self, name: str) -> str:
        return (self.snap / name).read_text().split("\n", 2)[2]  # without the generated-at line

    def test_writes_one_file_per_source(self):
        self.configure(table(name="a", type="fake", text="# A"), table(name="b", type="fake", text="# B"))
        self.assertEqual(self.refresh(), {"a.md": "ok", "b.md": "ok"})
        self.assertTrue((self.snap / "a.md").read_text().startswith("<!-- generated by remainderbot snapshot at "))
        self.assertEqual(self.body("a.md"), "# A\n")
        self.assertEqual(self.body("b.md"), "# B\n")
        self.assertEqual(self.logs, ["snapshot a.md: ok", "snapshot b.md: ok"])

    def test_a_failing_source_keeps_its_last_content_and_the_others_refresh(self):
        self.configure(table(name="a", type="fake", text="old"), table(name="b", type="fake", text="b1"))
        self.refresh()
        self.configure(table(name="a", type="fake", text="new", fail=True),
                       table(name="b", type="fake", text="b2", crash=True))
        status = self.refresh()
        self.assertEqual(status, {"a.md": "stale: fake: exit 1: down", "b.md": "stale: KeyError: 'oops'"})
        a = (self.snap / "a.md").read_text()
        self.assertTrue(a.startswith("stale: "), a)
        self.assertIn(": fake: exit 1: down\n\n<!-- generated by", a)
        self.assertTrue(a.endswith("\n\nold\n"), a)
        self.refresh()  # still failing: one stale line, not two
        self.assertEqual((self.snap / "a.md").read_text().count("stale: "), 1)

    def test_a_removed_or_disabled_source_loses_its_file(self):
        self.configure(table(name="a", type="fake", text="a"), table(name="b", type="fake", text="b"),
                       table(name="c", type="fake", text="c"))
        self.refresh()
        (self.snap / "notes.txt").write_text("not a snapshot file\n")
        self.configure(table(name="a", type="fake", text="a"), table(name="c", type="fake", text="c", enabled=False))
        self.assertEqual(self.refresh(), {"a.md": "ok"})
        self.assertEqual(sorted(p.name for p in self.snap.iterdir()), ["a.md", "notes.txt"])
        self.assertIn("snapshot b.md: deleted; no enabled source in sources.toml writes it", self.logs)

    def test_an_invalid_config_touches_nothing(self):
        self.configure(table(name="a", type="fake", text="a"))
        self.refresh()
        before = (self.snap / "a.md").read_text()
        self.configure(table(name="a", type="fake", text="a"), table(name="b", type="fake", txt="b"))
        with self.assertRaisesRegex(sources.ConfigError, r"^sources\.toml: source 'b': unknown field 'txt'"):
            self.refresh()
        self.assertEqual((self.snap / "a.md").read_text(), before)
        (self.td / "sources.toml").unlink()
        with self.assertRaisesRegex(sources.ConfigError, "not found"):
            self.refresh()
        self.assertEqual(sorted(p.name for p in self.snap.iterdir()), ["a.md"])

    def test_only_the_named_sources_refresh(self):
        self.configure(table(name="a", type="fake", text="a1"), table(name="b", type="fake", text="b1"),
                       table(name="c", type="fake", text="c1"))
        self.refresh()
        (self.snap / "gone.md").write_text("a removed source's file\n")
        self.configure(table(name="a", type="fake", text="a2"), table(name="b", type="fake", text="b2"),
                       table(name="c", type="fake", text="c2"))
        status = snapshot.refresh(self.config, self.logs.append, only=["c", "a", "c"])
        self.assertEqual(status, {"c.md": "ok", "a.md": "ok"})
        self.assertEqual((self.body("a.md"), self.body("b.md"), self.body("c.md")), ("a2\n", "b1\n", "c2\n"))
        self.assertTrue((self.snap / "gone.md").exists())  # only a full refresh deletes

    def test_a_name_that_is_not_an_enabled_source_is_an_error(self):
        self.configure(table(name="a", type="fake", text="a"), table(name="off", type="fake", text="x", enabled=False))
        with self.assertRaisesRegex(sources.ConfigError,
                                    r"^sources\.toml: no enabled source named 'off', 'nope'; enabled: a$"):
            snapshot.refresh(self.config, self.logs.append, only=["off", "nope"])
        self.assertFalse((self.snap / "a.md").exists())

    def test_cli_exit_codes(self):
        self.configure(table(name="a", type="fake", text="a"), table(name="b", type="fake", text="b", fail=True))
        with mock.patch.dict(os.environ, {"REPO_DIR": str(self.td)}), mock.patch.object(cli, "log", self.logs.append):
            self.assertEqual(cli.main(["snapshot", "--source", "a"]), 0)
            self.assertEqual(cli.main(["snapshot", "--source", "b"]), 1)
            self.assertEqual(cli.main(["snapshot", "--source", "c"]), 2)
        self.assertEqual(self.logs[-1], "sources.toml: no enabled source named 'c'; enabled: a, b")

    def test_max_chars_truncates_the_file(self):
        self.configure(table(name="a", type="fake", text="abcdefghij", max_chars=4))
        self.refresh()
        self.assertEqual(self.body("a.md"), "abcd\n\n[... truncated at 4 chars ...]\n")


if __name__ == "__main__":
    unittest.main()
