"""Refresh goals/snapshot/<name>.md for each source in sources.toml (DESIGN.md 3.1).

sources.toml is checked in full first; if it is invalid, refresh raises ConfigError and
touches nothing. Each source is then independent: if one fails, its file keeps the
previous content under a `stale: <error>` header and the others still refresh. A file
whose source is gone from sources.toml (or disabled) is deleted, so runs never copy it.
"""
from __future__ import annotations

import re
from datetime import datetime, timezone
from pathlib import Path

from . import sources as sources_mod
from .adapters import ADAPTERS, Context, SourceError
from .adapters._util import truncate
from .config import Config


def _stamp() -> str:
    return datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def _write(path: Path, content: str) -> None:
    path.write_text(f"<!-- generated by remainderbot snapshot at {_stamp()} -->\n\n" + content.rstrip() + "\n")


def _mark_stale(path: Path, error: str) -> None:
    old = path.read_text() if path.exists() else ""
    old = re.sub(r"^stale: .*\n\n?", "", old, count=1)
    path.write_text(f"stale: {_stamp()}: {error}\n\n" + old)


def refresh(config: Config, log=print, only: list[str] | None = None) -> dict[str, str]:
    """Write every enabled source's file, or only the named ones (for debugging a source;
    other files are left alone). Returns {filename: 'ok' | 'stale: <error>'}."""
    srcs = [s for s in sources_mod.load(config) if s.enabled]
    config.snapshot_dir.mkdir(parents=True, exist_ok=True)
    if only:
        srcs = _named(config, srcs, only)
    else:
        wanted = {s.filename for s in srcs}
        for path in sorted(config.snapshot_dir.glob("*.md")):
            if path.name not in wanted:
                path.unlink()
                log(f"snapshot {path.name}: deleted; no enabled source in {config.sources_file} writes it")
    status: dict[str, str] = {}
    for src in srcs:
        path = config.snapshot_dir / src.filename
        ctx = Context(repo_dir=config.repo_dir, max_chars=src.max_chars, log=log)
        try:
            _write(path, truncate(ADAPTERS[src.type].fn(src.fields, ctx), src.max_chars))
            status[src.filename] = "ok"
        except SourceError as e:
            _mark_stale(path, str(e))
            status[src.filename] = f"stale: {e}"
        except Exception as e:  # noqa: BLE001 - one bad source must not stop the others
            _mark_stale(path, f"{type(e).__name__}: {e}")
            status[src.filename] = f"stale: {type(e).__name__}: {e}"
        log(f"snapshot {src.filename}: {status[src.filename]}")
    return status


def _named(config: Config, enabled: list, names: list[str]) -> list:
    by_name = {s.name: s for s in enabled}
    missing = [n for n in names if n not in by_name]
    if missing:
        raise sources_mod.ConfigError(
            f"{config.sources_file}: no enabled source named {', '.join(map(repr, missing))}; "
            f"enabled: {', '.join(by_name) or 'none'}")
    return [by_name[n] for n in dict.fromkeys(names)]
